
import { Service, Product, Staff, Expense, Customer, DiscountCode, ShopSettings, Language } from './types';

export const CURRENCY_OPTIONS = [
  { label: 'US Dollar ($)', symbol: '$' },
  { label: 'Euro (€)', symbol: '€' },
  { label: 'British Pound (£)', symbol: '£' },
  { label: 'Pakistani Rupee (Rs.)', symbol: 'Rs.' },
  { label: 'Indian Rupee (₹)', symbol: '₹' },
  { label: 'UAE Dirham (د.إ)', symbol: 'د.إ' },
  { label: 'Saudi Riyal (ر.س)', symbol: 'ر.س' },
  { label: 'Canadian Dollar (C$)', symbol: 'C$' },
  { label: 'Australian Dollar (A$)', symbol: 'A$' },
];

export const DEFAULT_SETTINGS: ShopSettings = {
  shopName: 'TrimTime Barber',
  currency: '$',
  language: 'en',
  whatsappEnabled: true,
  whatsappNumber: '',
  receiptFooter: 'Thank you for choosing us!',
  taxRate: 8,
  taxType: 'excluded',
};

export const TRANSLATIONS = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    pos: 'POS Terminal',
    catalog: 'Catalog',
    customers: 'Customers',
    staff: 'Staff Management',
    finance: 'Finances',
    settings: 'Settings',
    logout: 'Logout',
    shopStatus: 'Shop Status',
    terminalLive: 'Terminal Live',
    
    // Dashboard
    performanceInsights: 'Performance Insights',
    welcomeBack: "Welcome back! Here's what's happening in your shop.",
    revenue: 'Revenue',
    expenses: 'Expenses',
    netProfit: 'Net Profit',
    avgTicket: 'Avg Ticket',
    revenueTrends: 'Revenue Trends',
    recentTransactions: 'Recent Transactions',
    waitingForSale: 'Waiting for first sale...',
    last7Days: 'Last 7 Days',

    // POS
    services: 'Services',
    products: 'Products',
    searchCatalog: 'Search catalog...',
    scanBarcode: 'Scan Barcode',
    stopScanning: 'Stop Scanning',
    cart: 'Cart',
    emptyCart: 'Empty Cart',
    subtotal: 'Subtotal',
    discount: 'Discount',
    tax: 'Tax',
    total: 'Total',
    cash: 'Cash',
    card: 'Card',
    holdBill: 'Hold Bill',
    heldBills: 'Held Bills',
    resume: 'Resume',
    saleSuccess: 'Sale Success',
    orderCompleted: 'Order completed.',
    shareReceipt: 'Share Receipt',
    downloadPdf: 'Download PDF',
    startNewBill: 'Start New Bill',
    chooseProfessional: 'Choose Professional...',
    walkInClient: 'Walk-in Client',
    quickAddClient: 'Quick Add Client',
    addSelectClient: 'Add & Select Client',
    name: 'Name',
    mobile: 'Mobile',
    email: 'Email',
    optional: 'Optional',

    // Finance
    shopPerformance: 'Shop Performance',
    commissionReport: 'Commission Report',
    payrollReport: 'Generate payroll reports by date range.',
    newExpense: 'New Expense',
    history: 'History',
    periodRevenue: 'Period Revenue',
    totalPayout: 'Total Payout',
    professional: 'Professional',
    salesCount: 'Sales Count',
    totalSales: 'Total Sales',
    payout: 'Payout',
    rate: 'Rate',
    category: 'Category',
    amount: 'Amount',
    details: 'Details',
    addExpense: 'Add Expense',
    smartInsights: 'Smart AI Insights',
    generateAdvice: 'Generate Advice',
    analyzing: 'Analyzing...',
    aiPrompt: 'Tap "Generate Advice" for a personalized business analysis.',
    noSalesPeriod: 'No sales found in this period.',
    noRecords: 'No records found.',
    noteDetails: 'Note down any details...',

    // Customers
    directory: 'Directory',
    clientProfiles: 'Client profiles and history.',
    addClient: 'Add Client',
    searchClients: 'Search clients...',
    visits: 'Visits',
    lifetime: 'Lifetime',
    lastSeen: 'Last Seen',
    stylePreferences: 'Style Preferences',
    noNotes: 'No notes on file.',
    date: 'Date',
    items: 'Items',
    registerClient: 'Register Client',
    createProfile: 'Create Profile',
    pickClient: 'Pick a client to review their grooming history.',
    member: 'Member',
    vip: 'VIP',

    // Staff
    teamHub: 'Team Hub',
    manageAccess: 'Manage access and earnings.',
    addStaff: 'Add Staff',
    loginId: 'Login ID',
    role: 'Role',
    commission: 'Commission',
    actions: 'Actions',
    editProfessional: 'Edit Professional',
    addToTeam: 'Add to Team',
    fullName: 'Full Name',
    username: 'Username',
    password: 'Password',
    employee: 'Employee',
    admin: 'Admin',
    saveProfessional: 'Save Professional',
    updateProfessional: 'Update Professional',

    // Inventory
    shopCatalog: 'Shop Catalog',
    updatePrices: 'Update prices and stock.',
    newService: 'New Service',
    newProduct: 'New Product',
    inventory: 'Inventory',
    itemDetails: 'Item Details',
    stockStatus: 'Stock Status',
    price: 'Price',
    editEntry: 'Edit Entry',
    newEntry: 'New Entry',
    labelName: 'Label Name',
    barcode: 'Barcode',
    mins: 'Mins',
    cost: 'Cost',
    initialStock: 'Initial Stock',
    saveChanges: 'Save Changes',
    unitsLeft: 'Units left',
    session: 'session',

    // Settings
    fineTune: 'Fine-tune your shop and communications.',
    shopBranding: 'Shop Branding & Localization',
    terminalIdentity: 'Terminal Identity',
    language: 'Language',
    preferredCurrency: 'Preferred Currency',
    taxCalculation: 'Tax Calculation',
    taxRate: 'Tax Rate (%)',
    receiptFooter: 'Receipt Footer',
    whatsAppSummaries: 'WhatsApp Summaries',
    enableWhatsApp: 'Enable digital receipts via WhatsApp.',
    businessMobile: 'Business Mobile Number',
    resetChanges: 'Reset Changes',
    saveSettings: 'Save All Settings',
    excluded: 'Excluded',
    included: 'Included',
    customSymbol: 'Custom symbol...',

    // Login
    premiumAccess: 'Premium Terminal Access',
    securityKey: 'Security Key',
    enterDashboard: 'Enter Dashboard',
    authorizedUse: 'Authorized Use Only',
    contactAdmin: 'Contact System Admin',
    invalidLogin: 'Invalid username or password',
    stayLoggedIn: 'Stay logged in for 30 days',
  },
  ur: {
    // Navigation
    dashboard: 'ڈیش بورڈ',
    pos: 'پوائنٹ آف سیل',
    catalog: 'کیٹلاگ',
    customers: 'صارفین',
    staff: 'عملے کا انتظام',
    finance: 'مالیات',
    settings: 'ترتیبات',
    logout: 'لاگ آؤٹ',
    shopStatus: 'دکان کی حیثیت',
    terminalLive: 'ٹرمینل لائیو',

    // Dashboard
    performanceInsights: 'کارکردگی کا جائزہ',
    welcomeBack: 'خوش آمدید! آپ کی دکان میں کیا ہو رہا ہے۔',
    revenue: 'آمدنی',
    expenses: 'اخراجات',
    netProfit: 'خالص منافع',
    avgTicket: 'اوسط ٹکٹ',
    revenueTrends: 'آمدنی کا رجحان',
    recentTransactions: 'حالیہ لین دین',
    waitingForSale: 'پہلی فروخت کا انتظار...',
    last7Days: 'پچھلے 7 دن',

    // POS
    services: 'خدمات',
    products: 'مصنوعات',
    searchCatalog: 'کیٹلاگ تلاش کریں...',
    scanBarcode: 'بارکوڈ اسکین کریں',
    stopScanning: 'اسکیننگ روکیں',
    cart: 'ٹوکری',
    emptyCart: 'خالی ٹوکری',
    subtotal: 'ذیلی کل',
    discount: 'رعایت',
    tax: 'ٹیکس',
    total: 'کل',
    cash: 'نقد',
    card: 'کارڈ',
    holdBill: 'بل روکیں',
    heldBills: 'روکے گئے بل',
    resume: 'بحال کریں',
    saleSuccess: 'فروخت کامیاب',
    orderCompleted: 'آرڈر مکمل',
    shareReceipt: 'رسید شیئر کریں',
    downloadPdf: 'پی ڈی ایف ڈاؤن لوڈ',
    startNewBill: 'نیا بل شروع کریں',
    chooseProfessional: 'پیشہ ور منتخب کریں...',
    walkInClient: 'واک ان کلائنٹ',
    quickAddClient: 'فوری کلائنٹ شامل کریں',
    addSelectClient: 'شامل اور منتخب کریں',
    name: 'نام',
    mobile: 'موبائل',
    email: 'ای میل',
    optional: 'اختیاری',

    // Finance
    shopPerformance: 'دکان کی کارکردگی',
    commissionReport: 'کمیشن رپورٹ',
    payrollReport: 'تاریخ کی حد کے لحاظ سے پے رول رپورٹ تیار کریں۔',
    newExpense: 'نیا خرچ',
    history: 'تاریخچہ',
    periodRevenue: 'مدت کی آمدنی',
    totalPayout: 'کل ادائیگی',
    professional: 'پیشہ ور',
    salesCount: 'فروخت کی تعداد',
    totalSales: 'کل فروخت',
    payout: 'ادائیگی',
    rate: 'شرح',
    category: 'زمرہ',
    amount: 'رقم',
    details: 'تفصیلات',
    addExpense: 'خرچ شامل کریں',
    smartInsights: 'اسمارٹ AI بصیرت',
    generateAdvice: 'مشورہ حاصل کریں',
    analyzing: 'تجزیہ ہو رہا ہے...',
    aiPrompt: 'ذاتی کاروباری تجزیے کے لیے "مشورہ حاصل کریں" پر ٹیپ کریں۔',
    noSalesPeriod: 'اس مدت میں کوئی فروخت نہیں ہوئی۔',
    noRecords: 'کوئی ریکارڈ نہیں ملا۔',
    noteDetails: 'کوئی تفصیلات نوٹ کریں...',

    // Customers
    directory: 'ڈائریکٹری',
    clientProfiles: 'کلائنٹ پروفائلز اور تاریخ۔',
    addClient: 'کلائنٹ شامل کریں',
    searchClients: 'کلائنٹ تلاش کریں...',
    visits: 'دورے',
    lifetime: 'لائف ٹائم',
    lastSeen: 'آخری بار دیکھا',
    stylePreferences: 'اسٹائل کی ترجیحات',
    noNotes: 'فائل پر کوئی نوٹس نہیں ہیں۔',
    date: 'تاریخ',
    items: 'اشیاء',
    registerClient: 'کلائنٹ رجسٹر کریں',
    createProfile: 'پروفائل بنائیں',
    pickClient: 'گرومنگ کی تاریخ کا جائزہ لینے کے لیے کلائنٹ کا انتخاب کریں۔',
    member: 'ممبر',
    vip: 'وی آئی پی',

    // Staff
    teamHub: 'ٹیم ہب',
    manageAccess: 'رسائی اور کمائی کا انتظام کریں۔',
    addStaff: 'عملہ شامل کریں',
    loginId: 'لاگ ان آئی ڈی',
    role: 'عہدہ',
    commission: 'کمیسیون',
    actions: 'اقدامات',
    editProfessional: 'پیشہ ور میں ترمیم کریں',
    addToTeam: 'ٹیم میں شامل کریں',
    fullName: 'پورا نام',
    username: 'صارف کا نام',
    password: 'پاس ورڈ',
    employee: 'ملازم',
    admin: 'ایڈمن',
    saveProfessional: 'پیشہ ور کو محفوظ کریں',
    updateProfessional: 'پیشہ ور کو اپ ڈیٹ کریں',

    // Inventory
    shopCatalog: 'دکان کیٹلاگ',
    updatePrices: 'قیمتیں اور اسٹاک اپ ڈیٹ کریں۔',
    newService: 'نئی سروس',
    newProduct: 'نئی پروڈکٹ',
    inventory: 'انوینٹری',
    itemDetails: 'آئٹم کی تفصیلات',
    stockStatus: 'اسٹاک کی حیثیت',
    price: 'قیمت',
    editEntry: 'اندراج میں ترمیم کریں',
    newEntry: 'نیا اندراج',
    labelName: 'لیبل کا نام',
    barcode: 'بارکوڈ',
    mins: 'منٹ',
    cost: 'لاگت',
    initialStock: 'ابتدائی اسٹاک',
    saveChanges: 'تبدیلیاں محفوظ کریں',
    unitsLeft: 'یونٹس باقی',
    session: 'سیشن',

    // Settings
    fineTune: 'اپنی دکان اور مواصلات کو بہتر بنائیں۔',
    shopBranding: 'شاپ برانڈنگ اور لوکلائزیشن',
    terminalIdentity: 'ٹرمینل شناخت',
    language: 'زبان',
    preferredCurrency: 'پسندیدہ کرنسی',
    taxCalculation: 'ٹیکس کا حساب کتاب',
    taxRate: 'ٹیکس کی شرح (%)',
    receiptFooter: 'رسید فوٹر',
    whatsAppSummaries: 'واٹس ایپ خلاصے',
    enableWhatsApp: 'واٹس ایپ کے ذریعے ڈیجیٹل رسیدیں فعال کریں۔',
    businessMobile: 'کاروباری موبائل نمبر',
    resetChanges: 'تبدیلیاں دوبارہ ترتیب دیں',
    saveSettings: 'تمام ترتیبات محفوظ کریں',
    excluded: 'شامل نہیں',
    included: 'شامل',
    customSymbol: 'حسب ضرورت علامت...',

    // Login
    premiumAccess: 'پریمیم ٹرمینل تک رسائی',
    securityKey: 'سیکیورٹی کلید',
    enterDashboard: 'ڈیش بورڈ میں داخل ہوں',
    authorizedUse: 'صرف مجاز استعمال',
    contactAdmin: 'سسٹم ایڈمن سے رابطہ کریں',
    invalidLogin: 'غلط صارف نام یا پاس ورڈ',
    stayLoggedIn: '30 دن تک لاگ ان رہیں',
  },
  fa: {
    // Navigation
    dashboard: 'داشبورد',
    pos: 'پایانه فروش',
    catalog: 'فهرست خدمات',
    customers: 'مشتریان',
    staff: 'مدیریت کارکنان',
    finance: 'امور مالی',
    settings: 'تنظیمات',
    logout: 'خروج',
    shopStatus: 'وضعیت فروشگاه',
    terminalLive: 'ترمینال فعال',

    // Dashboard
    performanceInsights: 'بینش عملکرد',
    welcomeBack: 'خوش آمدید! نگاهی به وضعیت فروشگاه شما.',
    revenue: 'درآمد',
    expenses: 'هزینه‌ها',
    netProfit: 'سود خالص',
    avgTicket: 'میانگین سفارش',
    revenueTrends: 'روند درآمد',
    recentTransactions: 'تراکنش‌های اخیر',
    waitingForSale: 'منتظر اولین فروش...',
    last7Days: '۷ روز گذشته',

    // POS
    services: 'خدمات',
    products: 'محصولات',
    searchCatalog: 'جستجوی فهرست...',
    scanBarcode: 'اسکن بارکد',
    stopScanning: 'توقف اسکن',
    cart: 'سبد خرید',
    emptyCart: 'سبد خالی',
    subtotal: 'جمع جزء',
    discount: 'تخفیف',
    tax: 'مالیات',
    total: 'مجموع',
    cash: 'نقد',
    card: 'کارت',
    holdBill: 'تعلیق فاکتور',
    heldBills: 'فاکتورهای معلق',
    resume: 'ادامه',
    saleSuccess: 'فروش موفق',
    orderCompleted: 'سفارش تکمیل شد.',
    shareReceipt: 'اشتراک رسید',
    downloadPdf: 'دانلود PDF',
    startNewBill: 'شروع فاکتور جدید',
    chooseProfessional: 'انتخاب متخصص...',
    walkInClient: 'مشتری حضوری',
    quickAddClient: 'افزودن سریع مشتری',
    addSelectClient: 'افزودن و انتخاب',
    name: 'نام',
    mobile: 'موبایل',
    email: 'ایمیل',
    optional: 'اختیاری',

    // Finance
    shopPerformance: 'عملکرد فروشگاه',
    commissionReport: 'گزارش کمیسیون',
    payrollReport: 'ایجاد گزارش حقوق و دستمزد بر اساس تاریخ.',
    newExpense: 'هزینه جدید',
    history: 'تاریخچه',
    periodRevenue: 'درآمد دوره',
    totalPayout: 'مجموع پرداختی',
    professional: 'متخصص',
    salesCount: 'تعداد فروش',
    totalSales: 'مجموع فروش',
    payout: 'پرداختی',
    rate: 'نرخ',
    category: 'دسته',
    amount: 'مبلغ',
    details: 'جزئیات',
    addExpense: 'افزودن هزینه',
    smartInsights: 'هوش مصنوعی',
    generateAdvice: 'تولید مشاوره',
    analyzing: 'در حال تحلیل...',
    aiPrompt: 'برای تحلیل کسب و کار روی "تولید مشاوره" ضربه بزنید.',
    noSalesPeriod: 'فروشی در این دوره یافت نشد.',
    noRecords: 'رکوردی یافت نشد.',
    noteDetails: 'یادداشت جزئیات...',

    // Customers
    directory: 'دفترچه',
    clientProfiles: 'پروفایل و تاریخچه مشتریان.',
    addClient: 'افزودن مشتری',
    searchClients: 'جستجوی مشتری...',
    visits: 'بازدیدها',
    lifetime: 'مادام‌العمر',
    lastSeen: 'آخرین بازدید',
    stylePreferences: 'ترجیحات استایل',
    noNotes: 'یادداشتی موجود نیست.',
    date: 'تاریخ',
    items: 'اقلام',
    registerClient: 'ثبت مشتری',
    createProfile: 'ایجاد پروفایل',
    pickClient: 'مشتری را برای بررسی تاریخچه انتخاب کنید.',
    member: 'عضو',
    vip: 'ویژه',

    // Staff
    teamHub: 'تیم ما',
    manageAccess: 'مدیریت دسترسی و درآمد.',
    addStaff: 'افزودن پرسنل',
    loginId: 'شناسه ورود',
    role: 'نقش',
    commission: 'کمیسیون',
    actions: 'عملیات',
    editProfessional: 'ویرایش متخصص',
    addToTeam: 'افزودن به تیم',
    fullName: 'نام کامل',
    username: 'نام کاربری',
    password: 'رمز عبور',
    employee: 'کارمند',
    admin: 'مدیر',
    saveProfessional: 'ذخیره متخصص',
    updateProfessional: 'بروزرسانی متخصص',

    // Inventory
    shopCatalog: 'فهرست فروشگاه',
    updatePrices: 'بروزرسانی قیمت و موجودی.',
    newService: 'خدمت جدید',
    newProduct: 'محصول جدید',
    inventory: 'انبار',
    itemDetails: 'جزئیات آیتم',
    stockStatus: 'وضعیت موجودی',
    price: 'قیمت',
    editEntry: 'ویرایش ورودی',
    newEntry: 'ورودی جدید',
    labelName: 'نام برچسب',
    barcode: 'بارکد',
    mins: 'دقیقه',
    cost: 'هزینه',
    initialStock: 'موجودی اولیه',
    saveChanges: 'ذخیره تغییرات',
    unitsLeft: 'عدد باقی‌مانده',
    session: 'جلسه',

    // Settings
    fineTune: 'تنظیمات فروشگاه و ارتباطات.',
    shopBranding: 'برندینگ و بومی‌سازی',
    terminalIdentity: 'هویت ترمینال',
    language: 'زبان',
    preferredCurrency: 'ارز ترجیحی',
    taxCalculation: 'محاسبه مالیات',
    taxRate: 'نرخ مالیات (%)',
    receiptFooter: 'پاورقی رسید',
    whatsAppSummaries: 'خلاصه واتساپ',
    enableWhatsApp: 'فعالسازی رسید دیجیتال در واتساپ.',
    businessMobile: 'شماره موبایل تجاری',
    resetChanges: 'بازنشانی تغییرات',
    saveSettings: 'ذخیره تنظیمات',
    excluded: 'مستثنی',
    included: 'شامل',
    customSymbol: 'نماد سفارشی...',

    // Login
    premiumAccess: 'دسترسی ترمینال ویژه',
    securityKey: 'کلید امنیتی',
    enterDashboard: 'ورود به داشبورد',
    authorizedUse: 'فقط استفاده مجاز',
    contactAdmin: 'تماس با مدیر سیستم',
    invalidLogin: 'نام کاربری یا رمز عبور نامعتبر',
    stayLoggedIn: 'برای ۳۰ روز وارد بمانید',
  }
};

export const INITIAL_SERVICES: Service[] = [
  { id: 's1', name: 'Classic Haircut', price: 35, duration: 30, category: 'Hair' },
  { id: 's2', name: 'Skin Fade', price: 45, duration: 45, category: 'Hair' },
  { id: 's3', name: 'Beard Trim', price: 20, duration: 20, category: 'Beard' },
  { id: 's4', name: 'Luxury Shave', price: 50, duration: 60, category: 'Shave' },
  { id: 's5', name: 'Kid\'s Cut', price: 25, duration: 30, category: 'Hair' },
  { id: 's6', name: 'Head Shave', price: 30, duration: 30, category: 'Hair' },
];

export const INITIAL_PRODUCTS: Product[] = [
  { id: 'p1', name: 'Pomade Matte', price: 18, cost: 8, stock: 24, barcode: '123456789012' },
  { id: 'p2', name: 'Beard Oil', price: 22, cost: 10, stock: 15, barcode: '098765432109' },
  { id: 'p3', name: 'Aftershave Balm', price: 25, cost: 12, stock: 10, barcode: '112233445566' },
  { id: 'p4', name: 'Texture Spray', price: 20, cost: 9, stock: 8, barcode: '665544332211' },
];

export const INITIAL_STAFF: Staff[] = [
  { id: 'st1', name: 'Admin User', role: 'admin', commission: 0, username: '1234', password: '1234' },
  { id: 'st2', name: 'Alex Rivers', role: 'employee', commission: 40, username: 'alex', password: 'password123' },
];

export const INITIAL_EXPENSES: Expense[] = [
  { id: 'e1', date: '2024-05-01', category: 'Rent', amount: 2000, description: 'Monthly Shop Rent' },
  { id: 'e2', date: '2024-05-02', category: 'Utilities', amount: 350, description: 'Electricity & Water' },
  { id: 'e3', date: '2024-05-05', category: 'Supplies', amount: 150, description: 'Towels & Cleaning' },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  { id: 'c1', name: 'John Smith', phone: '555-0101', email: 'john@example.com', notes: 'Likes a low taper fade.', createdAt: '2024-01-15' },
  { id: 'c2', name: 'Marcus Brown', phone: '555-0102', email: 'marcus@example.com', notes: 'Grows beard long.', createdAt: '2024-02-20' },
];

export const INITIAL_DISCOUNT_CODES: DiscountCode[] = [
  { code: 'WELCOME10', type: 'percentage', value: 10, description: '10% off for new customers' },
  { code: 'VIP20', type: 'percentage', value: 20, description: '20% off for VIP members' },
  { code: 'SAVE5', type: 'fixed', value: 5, description: '$5 off total' },
];
